### PR TITLE
feat: update grafana operator

### PR DESCRIPTION
**Pull request by rlanore**
### What does this PR do?

Update grafana operator to 5.5.2 release.

Take care of i had to use main branch to aws-observability-accelerator repo since we haven't tag tu support this operator version. [here](https://github.com/aws-observability/aws-observability-accelerator/pull/36)

### Motivation
Permit to use **configMapRef** into grafana dashboard manifest

see #246 

### More

- [x] Yes, I have tested the PR using my local account setup  (Provide any test evidence report under Additional Notes)
- [x] Yes, I ran `pre-commit run -a` with this PR

### For Moderators
- [ ] E2E Test successfully complete before merge?

### CODE REVIEW

**Comment by bonclay7** [comment]
Thanks for the PR @rlanore, can we use this tag instead of `main` https://github.com/aws-observability/aws-observability-accelerator/releases/tag/v0.3.1

**Review by bonclay7 — CHANGES_REQUESTED** [review]
Let's continue to use tags. I've released a new tag that include your changes https://github.com/aws-observability/aws-observability-accelerator/releases/tag/v0.3.1

**Comment by rlanore** [comment]
hi,
No problem i can change to still use tag.I pushed this change just now
Tested on my account every kustomization reconciliated

```
grafana-dashboards-adothealth                     True                 Applied revision: v0.3.1@sha1:b39123f0bd441015ff23bb342fdb63a6b51b0b2e
... ...
```

**Review by bonclay7 — APPROVED** [review]
TY!

**Pull request merged**
